



### this contains instructions not yet included in the dockerfile


pip install https://github.com/kpu/kenlm/archive/master.zip

========== instructions for kenlm ===============

# Prerequisites
sudo apt install cmake build-essential
apt -y install libboost-all-dev

# Clone and build
git clone https://github.com/kpu/kenlm.git
cd kenlm
mkdir build && cd build
cmake ..
make -j4

pip install nltk
pip install pyctcdecode




